--------------------------------------------------------
--  File created - Sunday-November-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BASICNOTIFDEMOBUF
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BASICNOTIFDEMOBUF" 
   (	"ORDERNUMBER" VARCHAR2(100 BYTE), 
	"SENDER" VARCHAR2(100 BYTE), 
	"PRODUCTID" VARCHAR2(100 BYTE), 
	"PRODUCTNAME" VARCHAR2(100 BYTE), 
	"WM_ROWID" NUMBER(27,0), 
	"WM_SENDTIME" NUMBER(14,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BASICNOTIFDEMOBUF
SET DEFINE OFF;
