--------------------------------------------------------
--  File created - Sunday-November-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERFFDATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDERFFDATA" 
   (	"ORDERNO" VARCHAR2(100 BYTE), 
	"ORDERDATE" VARCHAR2(100 BYTE), 
	"QUANTITY" VARCHAR2(100 BYTE), 
	"PRICE" VARCHAR2(100 BYTE), 
	"VAT" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ORDERFFDATA
SET DEFINE OFF;
