--------------------------------------------------------
--  File created - Sunday-November-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENT" 
   (	"STUDENTNAME" VARCHAR2(20 BYTE), 
	"STUDENTROLLNO" VARCHAR2(20 BYTE), 
	"FL" VARCHAR2(3 BYTE), 
	"ENGLISH" VARCHAR2(3 BYTE), 
	"MATHS" VARCHAR2(3 BYTE), 
	"SCIENCE" VARCHAR2(3 BYTE), 
	"SOCIAL" VARCHAR2(3 BYTE), 
	"TOTALMARKS" VARCHAR2(3 BYTE), 
	"PERCENTAGE" VARCHAR2(3 BYTE), 
	"GRADE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.STUDENT
SET DEFINE OFF;
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('A','01','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('B','02','40','40','40','70','70','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('30','03','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('A','01','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('B','02','40','40','40','70','70','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('C','03','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('D','01','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values (null,null,null,null,null,null,null,null,null,null);
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values (null,null,null,null,null,null,null,null,null,null);
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values (null,null,null,null,null,null,null,null,null,null);
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('E','90','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('F','80','80','30','80','40','30','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('G','30','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('H','01','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('I','02','40','40','40','70','70','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('J','03','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Z','90','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('X','80','80','30','80','40','30','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Y','30','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('ZZ','90','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('XS','80','80','30','80','40','30','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('YA','30','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('ZZZ','90','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('XSS','80','80','30','80','40','30','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('YAT','30','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('ZZZZ','90','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('XSSS','80','80','30','80','40','30','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('YATA','30','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('ABHIJITH','90','90','90','90','90','90','450','90','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('GANESH','80','80','30','80','40','30','260','52','Second Class');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('MANOJ','30','30','30','30','30','30','150','30','Fail');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Swetha','01','100','100','100','100','100','500','100','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Akshay','02','100','100','100','100','100','500','100','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Swetha','01','100','100','100','100','100','500','100','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Akshay','02','100','100','100','100','100','500','100','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Swetha1','01','100','100','100','100','100','500','100','Distinction');
Insert into SYSTEM.STUDENT (STUDENTNAME,STUDENTROLLNO,FL,ENGLISH,MATHS,SCIENCE,SOCIAL,TOTALMARKS,PERCENTAGE,GRADE) values ('Akshay1','02','100','100','100','100','100','500','100','Distinction');
